spring:
  #  datasource:
  #    username: root
  #    password: root
  #    driverClassName: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/social_media?useSSL=false&createDatabaseIfNotExist=true

  profiles:
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  file:
    name: app.log

  level:
    org:
      springframework:
        security: TRACE
