spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_media?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#  main: allow-circular-references=true
  main:
    allow-circular-references: true
